<?xml version="1.0" encoding="utf-8"?><Database Name="wesela" Class="klasy_linqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=wesela;Integrated Security=True" SettingsObjectName="wesela.Properties.Settings" SettingsPropertyName="weselaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.fotografowie_i_kamerzysci" Member="fotografowie_i_kamerzyscis">
    <Type Name="fotografowie_i_kamerzysci">
      <Column Name="id_fotografa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="czy_fotograf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="czy_kamerzysta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stawka_za_h" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="fotografowie_i_kamerzysci_wesela" Member="weselas" ThisKey="id_fotografa" OtherKey="id_fotografa" Type="wesela" />
      <Association Name="osoby_fotografowie_i_kamerzysci" Member="osoby" ThisKey="id_fotografa" OtherKey="id_osoby" Type="osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.goscie" Member="goscies">
    <Type Name="goscie">
      <Column Name="id_goscia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_prezentu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="liczba_osob_towarzyszacych" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_wesela" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="prezenty_goscie" Member="prezenty" ThisKey="id_prezentu" OtherKey="id_prezentu" Type="prezenty" IsForeignKey="true" />
      <Association Name="wesela_goscie" Member="wesela" ThisKey="id_wesela" OtherKey="id_wesela" Type="wesela" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.orkiestry" Member="orkiestries">
    <Type Name="orkiestry">
      <Column Name="id_orkiestry" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ilosc_osob_w_zespole" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="telefon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cena" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="orkiestry_wesela" Member="weselas" ThisKey="id_orkiestry" OtherKey="id_orkiestry" Type="wesela" />
    </Type>
  </Table>
  <Table Name="dbo.osoby" Member="osobies">
    <Type Name="osoby">
      <Column Name="id_osoby" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="imie" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="nazwisko" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="plec" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="adres" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="osoby_fotografowie_i_kamerzysci" Member="fotografowie_i_kamerzysci" ThisKey="id_osoby" OtherKey="id_fotografa" Type="fotografowie_i_kamerzysci" Cardinality="One" />
      <Association Name="osoby_pary_mlode" Member="pary_mlodes" ThisKey="id_osoby" OtherKey="id_meza" Type="pary_mlode" />
      <Association Name="osoby_pary_mlode1" Member="pary_mlodes1" ThisKey="id_osoby" OtherKey="id_zony" Type="pary_mlode" />
      <Association Name="osoby_sale" Member="sales" ThisKey="id_osoby" OtherKey="osoba_kontaktowa" Type="sale" />
    </Type>
  </Table>
  <Table Name="dbo.pary_mlode" Member="pary_mlodes">
    <Type Name="pary_mlode">
      <Column Name="id_pary" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_zony" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_meza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="budzet" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="pary_mlode_wesela" Member="weselas" ThisKey="id_pary" OtherKey="id_pary" Type="wesela" />
      <Association Name="osoby_pary_mlode" Member="osoby" ThisKey="id_meza" OtherKey="id_osoby" Type="osoby" IsForeignKey="true" />
      <Association Name="osoby_pary_mlode1" Member="osoby1" ThisKey="id_zony" OtherKey="id_osoby" Type="osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.prezenty" Member="prezenties">
    <Type Name="prezenty">
      <Column Name="id_prezentu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="opis_prezentu" Type="System.String" DbType="VarChar(5000) NOT NULL" CanBeNull="false" />
      <Association Name="prezenty_goscie" Member="goscies" ThisKey="id_prezentu" OtherKey="id_prezentu" Type="goscie" />
    </Type>
  </Table>
  <Table Name="dbo.rachunki" Member="rachunkis">
    <Type Name="rachunki">
      <Column Name="id_rachunku" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nr_konta" Type="System.String" DbType="VarChar(26) NOT NULL" CanBeNull="false" />
      <Column Name="kwota" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="termin_zaplaty" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="data_wplaty" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="rachunki_wesela" Member="weselas" ThisKey="id_rachunku" OtherKey="id_rachunku" Type="wesela" />
    </Type>
  </Table>
  <Table Name="dbo.sale" Member="sales">
    <Type Name="sale">
      <Column Name="id_sali" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="liczba_miejsc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="adres" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="cena_za_osobe" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="osoba_kontaktowa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="link" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Association Name="sale_wesela" Member="weselas" ThisKey="id_sali" OtherKey="id_sali" Type="wesela" />
      <Association Name="osoby_sale" Member="osoby" ThisKey="osoba_kontaktowa" OtherKey="id_osoby" Type="osoby" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.wesela" Member="weselas">
    <Type Name="wesela">
      <Column Name="id_wesela" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[_data]" Member="_data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_pary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="liczba_gosci" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_sali" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_fotografa" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_orkiestry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_rachunku" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="wesela_goscie" Member="goscies" ThisKey="id_wesela" OtherKey="id_wesela" Type="goscie" />
      <Association Name="fotografowie_i_kamerzysci_wesela" Member="fotografowie_i_kamerzysci" ThisKey="id_fotografa" OtherKey="id_fotografa" Type="fotografowie_i_kamerzysci" IsForeignKey="true" />
      <Association Name="orkiestry_wesela" Member="orkiestry" ThisKey="id_orkiestry" OtherKey="id_orkiestry" Type="orkiestry" IsForeignKey="true" />
      <Association Name="pary_mlode_wesela" Member="pary_mlode" ThisKey="id_pary" OtherKey="id_pary" Type="pary_mlode" IsForeignKey="true" />
      <Association Name="rachunki_wesela" Member="rachunki" ThisKey="id_rachunku" OtherKey="id_rachunku" Type="rachunki" IsForeignKey="true" />
      <Association Name="sale_wesela" Member="sale" ThisKey="id_sali" OtherKey="id_sali" Type="sale" IsForeignKey="true" />
    </Type>
  </Table>
</Database>