#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wesela
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="wesela")]
	public partial class klasy_linqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertfotografowie_i_kamerzysci(fotografowie_i_kamerzysci instance);
    partial void Updatefotografowie_i_kamerzysci(fotografowie_i_kamerzysci instance);
    partial void Deletefotografowie_i_kamerzysci(fotografowie_i_kamerzysci instance);
    partial void Insertgoscie(goscie instance);
    partial void Updategoscie(goscie instance);
    partial void Deletegoscie(goscie instance);
    partial void Insertorkiestry(orkiestry instance);
    partial void Updateorkiestry(orkiestry instance);
    partial void Deleteorkiestry(orkiestry instance);
    partial void Insertosoby(osoby instance);
    partial void Updateosoby(osoby instance);
    partial void Deleteosoby(osoby instance);
    partial void Insertpary_mlode(pary_mlode instance);
    partial void Updatepary_mlode(pary_mlode instance);
    partial void Deletepary_mlode(pary_mlode instance);
    partial void Insertprezenty(prezenty instance);
    partial void Updateprezenty(prezenty instance);
    partial void Deleteprezenty(prezenty instance);
    partial void Insertrachunki(rachunki instance);
    partial void Updaterachunki(rachunki instance);
    partial void Deleterachunki(rachunki instance);
    partial void Insertsale(sale instance);
    partial void Updatesale(sale instance);
    partial void Deletesale(sale instance);
    partial void Insertwesela(wesela instance);
    partial void Updatewesela(wesela instance);
    partial void Deletewesela(wesela instance);
    #endregion
		
		public klasy_linqDataContext() : 
				base(global::wesela.Properties.Settings.Default.weselaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public klasy_linqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public klasy_linqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public klasy_linqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public klasy_linqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fotografowie_i_kamerzysci> fotografowie_i_kamerzyscis
		{
			get
			{
				return this.GetTable<fotografowie_i_kamerzysci>();
			}
		}
		
		public System.Data.Linq.Table<goscie> goscies
		{
			get
			{
				return this.GetTable<goscie>();
			}
		}
		
		public System.Data.Linq.Table<orkiestry> orkiestries
		{
			get
			{
				return this.GetTable<orkiestry>();
			}
		}
		
		public System.Data.Linq.Table<osoby> osobies
		{
			get
			{
				return this.GetTable<osoby>();
			}
		}
		
		public System.Data.Linq.Table<pary_mlode> pary_mlodes
		{
			get
			{
				return this.GetTable<pary_mlode>();
			}
		}
		
		public System.Data.Linq.Table<prezenty> prezenties
		{
			get
			{
				return this.GetTable<prezenty>();
			}
		}
		
		public System.Data.Linq.Table<rachunki> rachunkis
		{
			get
			{
				return this.GetTable<rachunki>();
			}
		}
		
		public System.Data.Linq.Table<sale> sales
		{
			get
			{
				return this.GetTable<sale>();
			}
		}
		
		public System.Data.Linq.Table<wesela> weselas
		{
			get
			{
				return this.GetTable<wesela>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fotografowie_i_kamerzysci")]
	public partial class fotografowie_i_kamerzysci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_fotografa;
		
		private int _czy_fotograf;
		
		private int _czy_kamerzysta;
		
		private System.Nullable<decimal> _stawka_za_h;
		
		private string _link;
		
		private EntitySet<wesela> _weselas;
		
		private EntityRef<osoby> _osoby;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_fotografaChanging(int value);
    partial void Onid_fotografaChanged();
    partial void Onczy_fotografChanging(int value);
    partial void Onczy_fotografChanged();
    partial void Onczy_kamerzystaChanging(int value);
    partial void Onczy_kamerzystaChanged();
    partial void Onstawka_za_hChanging(System.Nullable<decimal> value);
    partial void Onstawka_za_hChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public fotografowie_i_kamerzysci()
		{
			this._weselas = new EntitySet<wesela>(new Action<wesela>(this.attach_weselas), new Action<wesela>(this.detach_weselas));
			this._osoby = default(EntityRef<osoby>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fotografa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_fotografa
		{
			get
			{
				return this._id_fotografa;
			}
			set
			{
				if ((this._id_fotografa != value))
				{
					if (this._osoby.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fotografaChanging(value);
					this.SendPropertyChanging();
					this._id_fotografa = value;
					this.SendPropertyChanged("id_fotografa");
					this.Onid_fotografaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_fotograf", DbType="Int NOT NULL")]
		public int czy_fotograf
		{
			get
			{
				return this._czy_fotograf;
			}
			set
			{
				if ((this._czy_fotograf != value))
				{
					this.Onczy_fotografChanging(value);
					this.SendPropertyChanging();
					this._czy_fotograf = value;
					this.SendPropertyChanged("czy_fotograf");
					this.Onczy_fotografChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_czy_kamerzysta", DbType="Int NOT NULL")]
		public int czy_kamerzysta
		{
			get
			{
				return this._czy_kamerzysta;
			}
			set
			{
				if ((this._czy_kamerzysta != value))
				{
					this.Onczy_kamerzystaChanging(value);
					this.SendPropertyChanging();
					this._czy_kamerzysta = value;
					this.SendPropertyChanged("czy_kamerzysta");
					this.Onczy_kamerzystaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stawka_za_h", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> stawka_za_h
		{
			get
			{
				return this._stawka_za_h;
			}
			set
			{
				if ((this._stawka_za_h != value))
				{
					this.Onstawka_za_hChanging(value);
					this.SendPropertyChanging();
					this._stawka_za_h = value;
					this.SendPropertyChanged("stawka_za_h");
					this.Onstawka_za_hChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(250)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fotografowie_i_kamerzysci_wesela", Storage="_weselas", ThisKey="id_fotografa", OtherKey="id_fotografa")]
		public EntitySet<wesela> weselas
		{
			get
			{
				return this._weselas;
			}
			set
			{
				this._weselas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_fotografowie_i_kamerzysci", Storage="_osoby", ThisKey="id_fotografa", OtherKey="id_osoby", IsForeignKey=true)]
		public osoby osoby
		{
			get
			{
				return this._osoby.Entity;
			}
			set
			{
				osoby previousValue = this._osoby.Entity;
				if (((previousValue != value) 
							|| (this._osoby.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._osoby.Entity = null;
						previousValue.fotografowie_i_kamerzysci = null;
					}
					this._osoby.Entity = value;
					if ((value != null))
					{
						value.fotografowie_i_kamerzysci = this;
						this._id_fotografa = value.id_osoby;
					}
					else
					{
						this._id_fotografa = default(int);
					}
					this.SendPropertyChanged("osoby");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.fotografowie_i_kamerzysci = this;
		}
		
		private void detach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.fotografowie_i_kamerzysci = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.goscie")]
	public partial class goscie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_goscia;
		
		private System.Nullable<int> _id_prezentu;
		
		private System.Nullable<int> _liczba_osob_towarzyszacych;
		
		private int _id_wesela;
		
		private EntityRef<prezenty> _prezenty;
		
		private EntityRef<wesela> _wesela;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_gosciaChanging(int value);
    partial void Onid_gosciaChanged();
    partial void Onid_prezentuChanging(System.Nullable<int> value);
    partial void Onid_prezentuChanged();
    partial void Onliczba_osob_towarzyszacychChanging(System.Nullable<int> value);
    partial void Onliczba_osob_towarzyszacychChanged();
    partial void Onid_weselaChanging(int value);
    partial void Onid_weselaChanged();
    #endregion
		
		public goscie()
		{
			this._prezenty = default(EntityRef<prezenty>);
			this._wesela = default(EntityRef<wesela>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_goscia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_goscia
		{
			get
			{
				return this._id_goscia;
			}
			set
			{
				if ((this._id_goscia != value))
				{
					this.Onid_gosciaChanging(value);
					this.SendPropertyChanging();
					this._id_goscia = value;
					this.SendPropertyChanged("id_goscia");
					this.Onid_gosciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prezentu", DbType="Int")]
		public System.Nullable<int> id_prezentu
		{
			get
			{
				return this._id_prezentu;
			}
			set
			{
				if ((this._id_prezentu != value))
				{
					if (this._prezenty.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_prezentuChanging(value);
					this.SendPropertyChanging();
					this._id_prezentu = value;
					this.SendPropertyChanged("id_prezentu");
					this.Onid_prezentuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liczba_osob_towarzyszacych", DbType="Int")]
		public System.Nullable<int> liczba_osob_towarzyszacych
		{
			get
			{
				return this._liczba_osob_towarzyszacych;
			}
			set
			{
				if ((this._liczba_osob_towarzyszacych != value))
				{
					this.Onliczba_osob_towarzyszacychChanging(value);
					this.SendPropertyChanging();
					this._liczba_osob_towarzyszacych = value;
					this.SendPropertyChanged("liczba_osob_towarzyszacych");
					this.Onliczba_osob_towarzyszacychChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_wesela", DbType="Int NOT NULL")]
		public int id_wesela
		{
			get
			{
				return this._id_wesela;
			}
			set
			{
				if ((this._id_wesela != value))
				{
					if (this._wesela.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_weselaChanging(value);
					this.SendPropertyChanging();
					this._id_wesela = value;
					this.SendPropertyChanged("id_wesela");
					this.Onid_weselaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="prezenty_goscie", Storage="_prezenty", ThisKey="id_prezentu", OtherKey="id_prezentu", IsForeignKey=true)]
		public prezenty prezenty
		{
			get
			{
				return this._prezenty.Entity;
			}
			set
			{
				prezenty previousValue = this._prezenty.Entity;
				if (((previousValue != value) 
							|| (this._prezenty.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._prezenty.Entity = null;
						previousValue.goscies.Remove(this);
					}
					this._prezenty.Entity = value;
					if ((value != null))
					{
						value.goscies.Add(this);
						this._id_prezentu = value.id_prezentu;
					}
					else
					{
						this._id_prezentu = default(Nullable<int>);
					}
					this.SendPropertyChanged("prezenty");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="wesela_goscie", Storage="_wesela", ThisKey="id_wesela", OtherKey="id_wesela", IsForeignKey=true)]
		public wesela wesela
		{
			get
			{
				return this._wesela.Entity;
			}
			set
			{
				wesela previousValue = this._wesela.Entity;
				if (((previousValue != value) 
							|| (this._wesela.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._wesela.Entity = null;
						previousValue.goscies.Remove(this);
					}
					this._wesela.Entity = value;
					if ((value != null))
					{
						value.goscies.Add(this);
						this._id_wesela = value.id_wesela;
					}
					else
					{
						this._id_wesela = default(int);
					}
					this.SendPropertyChanged("wesela");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orkiestry")]
	public partial class orkiestry : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_orkiestry;
		
		private string _nazwa;
		
		private int _ilosc_osob_w_zespole;
		
		private int _telefon;
		
		private System.Nullable<decimal> _cena;
		
		private string _link;
		
		private EntitySet<wesela> _weselas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_orkiestryChanging(int value);
    partial void Onid_orkiestryChanged();
    partial void OnnazwaChanging(string value);
    partial void OnnazwaChanged();
    partial void Onilosc_osob_w_zespoleChanging(int value);
    partial void Onilosc_osob_w_zespoleChanged();
    partial void OntelefonChanging(int value);
    partial void OntelefonChanged();
    partial void OncenaChanging(System.Nullable<decimal> value);
    partial void OncenaChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public orkiestry()
		{
			this._weselas = new EntitySet<wesela>(new Action<wesela>(this.attach_weselas), new Action<wesela>(this.detach_weselas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_orkiestry", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_orkiestry
		{
			get
			{
				return this._id_orkiestry;
			}
			set
			{
				if ((this._id_orkiestry != value))
				{
					this.Onid_orkiestryChanging(value);
					this.SendPropertyChanging();
					this._id_orkiestry = value;
					this.SendPropertyChanged("id_orkiestry");
					this.Onid_orkiestryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwa", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string nazwa
		{
			get
			{
				return this._nazwa;
			}
			set
			{
				if ((this._nazwa != value))
				{
					this.OnnazwaChanging(value);
					this.SendPropertyChanging();
					this._nazwa = value;
					this.SendPropertyChanged("nazwa");
					this.OnnazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ilosc_osob_w_zespole", DbType="Int NOT NULL")]
		public int ilosc_osob_w_zespole
		{
			get
			{
				return this._ilosc_osob_w_zespole;
			}
			set
			{
				if ((this._ilosc_osob_w_zespole != value))
				{
					this.Onilosc_osob_w_zespoleChanging(value);
					this.SendPropertyChanging();
					this._ilosc_osob_w_zespole = value;
					this.SendPropertyChanged("ilosc_osob_w_zespole");
					this.Onilosc_osob_w_zespoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Int NOT NULL")]
		public int telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cena
		{
			get
			{
				return this._cena;
			}
			set
			{
				if ((this._cena != value))
				{
					this.OncenaChanging(value);
					this.SendPropertyChanging();
					this._cena = value;
					this.SendPropertyChanged("cena");
					this.OncenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(250)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orkiestry_wesela", Storage="_weselas", ThisKey="id_orkiestry", OtherKey="id_orkiestry")]
		public EntitySet<wesela> weselas
		{
			get
			{
				return this._weselas;
			}
			set
			{
				this._weselas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.orkiestry = this;
		}
		
		private void detach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.orkiestry = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.osoby")]
	public partial class osoby : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_osoby;
		
		private string _imie;
		
		private string _nazwisko;
		
		private char _plec;
		
		private System.Nullable<int> _tel;
		
		private string _email;
		
		private string _adres;
		
		private EntityRef<fotografowie_i_kamerzysci> _fotografowie_i_kamerzysci;
		
		private EntitySet<pary_mlode> _pary_mlodes;
		
		private EntitySet<pary_mlode> _pary_mlodes1;
		
		private EntitySet<sale> _sales;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_osobyChanging(int value);
    partial void Onid_osobyChanged();
    partial void OnimieChanging(string value);
    partial void OnimieChanged();
    partial void OnnazwiskoChanging(string value);
    partial void OnnazwiskoChanged();
    partial void OnplecChanging(char value);
    partial void OnplecChanged();
    partial void OntelChanging(System.Nullable<int> value);
    partial void OntelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    #endregion
		
		public osoby()
		{
			this._fotografowie_i_kamerzysci = default(EntityRef<fotografowie_i_kamerzysci>);
			this._pary_mlodes = new EntitySet<pary_mlode>(new Action<pary_mlode>(this.attach_pary_mlodes), new Action<pary_mlode>(this.detach_pary_mlodes));
			this._pary_mlodes1 = new EntitySet<pary_mlode>(new Action<pary_mlode>(this.attach_pary_mlodes1), new Action<pary_mlode>(this.detach_pary_mlodes1));
			this._sales = new EntitySet<sale>(new Action<sale>(this.attach_sales), new Action<sale>(this.detach_sales));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_osoby", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_osoby
		{
			get
			{
				return this._id_osoby;
			}
			set
			{
				if ((this._id_osoby != value))
				{
					this.Onid_osobyChanging(value);
					this.SendPropertyChanging();
					this._id_osoby = value;
					this.SendPropertyChanged("id_osoby");
					this.Onid_osobyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imie", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string imie
		{
			get
			{
				return this._imie;
			}
			set
			{
				if ((this._imie != value))
				{
					this.OnimieChanging(value);
					this.SendPropertyChanging();
					this._imie = value;
					this.SendPropertyChanged("imie");
					this.OnimieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nazwisko", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nazwisko
		{
			get
			{
				return this._nazwisko;
			}
			set
			{
				if ((this._nazwisko != value))
				{
					this.OnnazwiskoChanging(value);
					this.SendPropertyChanging();
					this._nazwisko = value;
					this.SendPropertyChanged("nazwisko");
					this.OnnazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plec", DbType="Char(1) NOT NULL")]
		public char plec
		{
			get
			{
				return this._plec;
			}
			set
			{
				if ((this._plec != value))
				{
					this.OnplecChanging(value);
					this.SendPropertyChanging();
					this._plec = value;
					this.SendPropertyChanged("plec");
					this.OnplecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="Int")]
		public System.Nullable<int> tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(250)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(100)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_fotografowie_i_kamerzysci", Storage="_fotografowie_i_kamerzysci", ThisKey="id_osoby", OtherKey="id_fotografa", IsUnique=true, IsForeignKey=false)]
		public fotografowie_i_kamerzysci fotografowie_i_kamerzysci
		{
			get
			{
				return this._fotografowie_i_kamerzysci.Entity;
			}
			set
			{
				fotografowie_i_kamerzysci previousValue = this._fotografowie_i_kamerzysci.Entity;
				if (((previousValue != value) 
							|| (this._fotografowie_i_kamerzysci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fotografowie_i_kamerzysci.Entity = null;
						previousValue.osoby = null;
					}
					this._fotografowie_i_kamerzysci.Entity = value;
					if ((value != null))
					{
						value.osoby = this;
					}
					this.SendPropertyChanged("fotografowie_i_kamerzysci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_pary_mlode", Storage="_pary_mlodes", ThisKey="id_osoby", OtherKey="id_meza")]
		public EntitySet<pary_mlode> pary_mlodes
		{
			get
			{
				return this._pary_mlodes;
			}
			set
			{
				this._pary_mlodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_pary_mlode1", Storage="_pary_mlodes1", ThisKey="id_osoby", OtherKey="id_zony")]
		public EntitySet<pary_mlode> pary_mlodes1
		{
			get
			{
				return this._pary_mlodes1;
			}
			set
			{
				this._pary_mlodes1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_sale", Storage="_sales", ThisKey="id_osoby", OtherKey="osoba_kontaktowa")]
		public EntitySet<sale> sales
		{
			get
			{
				return this._sales;
			}
			set
			{
				this._sales.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_pary_mlodes(pary_mlode entity)
		{
			this.SendPropertyChanging();
			entity.osoby = this;
		}
		
		private void detach_pary_mlodes(pary_mlode entity)
		{
			this.SendPropertyChanging();
			entity.osoby = null;
		}
		
		private void attach_pary_mlodes1(pary_mlode entity)
		{
			this.SendPropertyChanging();
			entity.osoby1 = this;
		}
		
		private void detach_pary_mlodes1(pary_mlode entity)
		{
			this.SendPropertyChanging();
			entity.osoby1 = null;
		}
		
		private void attach_sales(sale entity)
		{
			this.SendPropertyChanging();
			entity.osoby = this;
		}
		
		private void detach_sales(sale entity)
		{
			this.SendPropertyChanging();
			entity.osoby = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pary_mlode")]
	public partial class pary_mlode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_pary;
		
		private int _id_zony;
		
		private int _id_meza;
		
		private System.Nullable<decimal> _budzet;
		
		private EntitySet<wesela> _weselas;
		
		private EntityRef<osoby> _osoby;
		
		private EntityRef<osoby> _osoby1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_paryChanging(int value);
    partial void Onid_paryChanged();
    partial void Onid_zonyChanging(int value);
    partial void Onid_zonyChanged();
    partial void Onid_mezaChanging(int value);
    partial void Onid_mezaChanged();
    partial void OnbudzetChanging(System.Nullable<decimal> value);
    partial void OnbudzetChanged();
    #endregion
		
		public pary_mlode()
		{
			this._weselas = new EntitySet<wesela>(new Action<wesela>(this.attach_weselas), new Action<wesela>(this.detach_weselas));
			this._osoby = default(EntityRef<osoby>);
			this._osoby1 = default(EntityRef<osoby>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pary", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_pary
		{
			get
			{
				return this._id_pary;
			}
			set
			{
				if ((this._id_pary != value))
				{
					this.Onid_paryChanging(value);
					this.SendPropertyChanging();
					this._id_pary = value;
					this.SendPropertyChanged("id_pary");
					this.Onid_paryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_zony", DbType="Int NOT NULL")]
		public int id_zony
		{
			get
			{
				return this._id_zony;
			}
			set
			{
				if ((this._id_zony != value))
				{
					if (this._osoby1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_zonyChanging(value);
					this.SendPropertyChanging();
					this._id_zony = value;
					this.SendPropertyChanged("id_zony");
					this.Onid_zonyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_meza", DbType="Int NOT NULL")]
		public int id_meza
		{
			get
			{
				return this._id_meza;
			}
			set
			{
				if ((this._id_meza != value))
				{
					if (this._osoby.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_mezaChanging(value);
					this.SendPropertyChanging();
					this._id_meza = value;
					this.SendPropertyChanged("id_meza");
					this.Onid_mezaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_budzet", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> budzet
		{
			get
			{
				return this._budzet;
			}
			set
			{
				if ((this._budzet != value))
				{
					this.OnbudzetChanging(value);
					this.SendPropertyChanging();
					this._budzet = value;
					this.SendPropertyChanged("budzet");
					this.OnbudzetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pary_mlode_wesela", Storage="_weselas", ThisKey="id_pary", OtherKey="id_pary")]
		public EntitySet<wesela> weselas
		{
			get
			{
				return this._weselas;
			}
			set
			{
				this._weselas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_pary_mlode", Storage="_osoby", ThisKey="id_meza", OtherKey="id_osoby", IsForeignKey=true)]
		public osoby osoby
		{
			get
			{
				return this._osoby.Entity;
			}
			set
			{
				osoby previousValue = this._osoby.Entity;
				if (((previousValue != value) 
							|| (this._osoby.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._osoby.Entity = null;
						previousValue.pary_mlodes.Remove(this);
					}
					this._osoby.Entity = value;
					if ((value != null))
					{
						value.pary_mlodes.Add(this);
						this._id_meza = value.id_osoby;
					}
					else
					{
						this._id_meza = default(int);
					}
					this.SendPropertyChanged("osoby");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_pary_mlode1", Storage="_osoby1", ThisKey="id_zony", OtherKey="id_osoby", IsForeignKey=true)]
		public osoby osoby1
		{
			get
			{
				return this._osoby1.Entity;
			}
			set
			{
				osoby previousValue = this._osoby1.Entity;
				if (((previousValue != value) 
							|| (this._osoby1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._osoby1.Entity = null;
						previousValue.pary_mlodes1.Remove(this);
					}
					this._osoby1.Entity = value;
					if ((value != null))
					{
						value.pary_mlodes1.Add(this);
						this._id_zony = value.id_osoby;
					}
					else
					{
						this._id_zony = default(int);
					}
					this.SendPropertyChanged("osoby1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.pary_mlode = this;
		}
		
		private void detach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.pary_mlode = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.prezenty")]
	public partial class prezenty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_prezentu;
		
		private string _opis_prezentu;
		
		private EntitySet<goscie> _goscies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_prezentuChanging(int value);
    partial void Onid_prezentuChanged();
    partial void Onopis_prezentuChanging(string value);
    partial void Onopis_prezentuChanged();
    #endregion
		
		public prezenty()
		{
			this._goscies = new EntitySet<goscie>(new Action<goscie>(this.attach_goscies), new Action<goscie>(this.detach_goscies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_prezentu", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_prezentu
		{
			get
			{
				return this._id_prezentu;
			}
			set
			{
				if ((this._id_prezentu != value))
				{
					this.Onid_prezentuChanging(value);
					this.SendPropertyChanging();
					this._id_prezentu = value;
					this.SendPropertyChanged("id_prezentu");
					this.Onid_prezentuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis_prezentu", DbType="VarChar(5000) NOT NULL", CanBeNull=false)]
		public string opis_prezentu
		{
			get
			{
				return this._opis_prezentu;
			}
			set
			{
				if ((this._opis_prezentu != value))
				{
					this.Onopis_prezentuChanging(value);
					this.SendPropertyChanging();
					this._opis_prezentu = value;
					this.SendPropertyChanged("opis_prezentu");
					this.Onopis_prezentuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="prezenty_goscie", Storage="_goscies", ThisKey="id_prezentu", OtherKey="id_prezentu")]
		public EntitySet<goscie> goscies
		{
			get
			{
				return this._goscies;
			}
			set
			{
				this._goscies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_goscies(goscie entity)
		{
			this.SendPropertyChanging();
			entity.prezenty = this;
		}
		
		private void detach_goscies(goscie entity)
		{
			this.SendPropertyChanging();
			entity.prezenty = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rachunki")]
	public partial class rachunki : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_rachunku;
		
		private string _nr_konta;
		
		private decimal _kwota;
		
		private System.DateTime _termin_zaplaty;
		
		private System.Nullable<System.DateTime> _data_wplaty;
		
		private EntitySet<wesela> _weselas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_rachunkuChanging(int value);
    partial void Onid_rachunkuChanged();
    partial void Onnr_kontaChanging(string value);
    partial void Onnr_kontaChanged();
    partial void OnkwotaChanging(decimal value);
    partial void OnkwotaChanged();
    partial void Ontermin_zaplatyChanging(System.DateTime value);
    partial void Ontermin_zaplatyChanged();
    partial void Ondata_wplatyChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_wplatyChanged();
    #endregion
		
		public rachunki()
		{
			this._weselas = new EntitySet<wesela>(new Action<wesela>(this.attach_weselas), new Action<wesela>(this.detach_weselas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rachunku", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_rachunku
		{
			get
			{
				return this._id_rachunku;
			}
			set
			{
				if ((this._id_rachunku != value))
				{
					this.Onid_rachunkuChanging(value);
					this.SendPropertyChanging();
					this._id_rachunku = value;
					this.SendPropertyChanged("id_rachunku");
					this.Onid_rachunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nr_konta", DbType="VarChar(26) NOT NULL", CanBeNull=false)]
		public string nr_konta
		{
			get
			{
				return this._nr_konta;
			}
			set
			{
				if ((this._nr_konta != value))
				{
					this.Onnr_kontaChanging(value);
					this.SendPropertyChanging();
					this._nr_konta = value;
					this.SendPropertyChanged("nr_konta");
					this.Onnr_kontaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kwota", DbType="Decimal(18,0) NOT NULL")]
		public decimal kwota
		{
			get
			{
				return this._kwota;
			}
			set
			{
				if ((this._kwota != value))
				{
					this.OnkwotaChanging(value);
					this.SendPropertyChanging();
					this._kwota = value;
					this.SendPropertyChanged("kwota");
					this.OnkwotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_termin_zaplaty", DbType="DateTime NOT NULL")]
		public System.DateTime termin_zaplaty
		{
			get
			{
				return this._termin_zaplaty;
			}
			set
			{
				if ((this._termin_zaplaty != value))
				{
					this.Ontermin_zaplatyChanging(value);
					this.SendPropertyChanging();
					this._termin_zaplaty = value;
					this.SendPropertyChanged("termin_zaplaty");
					this.Ontermin_zaplatyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_wplaty", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_wplaty
		{
			get
			{
				return this._data_wplaty;
			}
			set
			{
				if ((this._data_wplaty != value))
				{
					this.Ondata_wplatyChanging(value);
					this.SendPropertyChanging();
					this._data_wplaty = value;
					this.SendPropertyChanged("data_wplaty");
					this.Ondata_wplatyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rachunki_wesela", Storage="_weselas", ThisKey="id_rachunku", OtherKey="id_rachunku")]
		public EntitySet<wesela> weselas
		{
			get
			{
				return this._weselas;
			}
			set
			{
				this._weselas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.rachunki = this;
		}
		
		private void detach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.rachunki = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sale")]
	public partial class sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_sali;
		
		private int _liczba_miejsc;
		
		private string _adres;
		
		private decimal _cena_za_osobe;
		
		private int _osoba_kontaktowa;
		
		private string _link;
		
		private EntitySet<wesela> _weselas;
		
		private EntityRef<osoby> _osoby;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_saliChanging(int value);
    partial void Onid_saliChanged();
    partial void Onliczba_miejscChanging(int value);
    partial void Onliczba_miejscChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    partial void Oncena_za_osobeChanging(decimal value);
    partial void Oncena_za_osobeChanged();
    partial void Onosoba_kontaktowaChanging(int value);
    partial void Onosoba_kontaktowaChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
		
		public sale()
		{
			this._weselas = new EntitySet<wesela>(new Action<wesela>(this.attach_weselas), new Action<wesela>(this.detach_weselas));
			this._osoby = default(EntityRef<osoby>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sali", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_sali
		{
			get
			{
				return this._id_sali;
			}
			set
			{
				if ((this._id_sali != value))
				{
					this.Onid_saliChanging(value);
					this.SendPropertyChanging();
					this._id_sali = value;
					this.SendPropertyChanged("id_sali");
					this.Onid_saliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liczba_miejsc", DbType="Int NOT NULL")]
		public int liczba_miejsc
		{
			get
			{
				return this._liczba_miejsc;
			}
			set
			{
				if ((this._liczba_miejsc != value))
				{
					this.Onliczba_miejscChanging(value);
					this.SendPropertyChanging();
					this._liczba_miejsc = value;
					this.SendPropertyChanged("liczba_miejsc");
					this.Onliczba_miejscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cena_za_osobe", DbType="Decimal(18,0) NOT NULL")]
		public decimal cena_za_osobe
		{
			get
			{
				return this._cena_za_osobe;
			}
			set
			{
				if ((this._cena_za_osobe != value))
				{
					this.Oncena_za_osobeChanging(value);
					this.SendPropertyChanging();
					this._cena_za_osobe = value;
					this.SendPropertyChanged("cena_za_osobe");
					this.Oncena_za_osobeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_osoba_kontaktowa", DbType="Int NOT NULL")]
		public int osoba_kontaktowa
		{
			get
			{
				return this._osoba_kontaktowa;
			}
			set
			{
				if ((this._osoba_kontaktowa != value))
				{
					if (this._osoby.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onosoba_kontaktowaChanging(value);
					this.SendPropertyChanging();
					this._osoba_kontaktowa = value;
					this.SendPropertyChanged("osoba_kontaktowa");
					this.Onosoba_kontaktowaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(250)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this.OnlinkChanging(value);
					this.SendPropertyChanging();
					this._link = value;
					this.SendPropertyChanged("link");
					this.OnlinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sale_wesela", Storage="_weselas", ThisKey="id_sali", OtherKey="id_sali")]
		public EntitySet<wesela> weselas
		{
			get
			{
				return this._weselas;
			}
			set
			{
				this._weselas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="osoby_sale", Storage="_osoby", ThisKey="osoba_kontaktowa", OtherKey="id_osoby", IsForeignKey=true)]
		public osoby osoby
		{
			get
			{
				return this._osoby.Entity;
			}
			set
			{
				osoby previousValue = this._osoby.Entity;
				if (((previousValue != value) 
							|| (this._osoby.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._osoby.Entity = null;
						previousValue.sales.Remove(this);
					}
					this._osoby.Entity = value;
					if ((value != null))
					{
						value.sales.Add(this);
						this._osoba_kontaktowa = value.id_osoby;
					}
					else
					{
						this._osoba_kontaktowa = default(int);
					}
					this.SendPropertyChanged("osoby");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.sale = this;
		}
		
		private void detach_weselas(wesela entity)
		{
			this.SendPropertyChanging();
			entity.sale = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.wesela")]
	public partial class wesela : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_wesela;
		
		private System.DateTime @__data;
		
		private int _id_pary;
		
		private int _liczba_gosci;
		
		private System.Nullable<int> _id_sali;
		
		private System.Nullable<int> _id_fotografa;
		
		private System.Nullable<int> _id_orkiestry;
		
		private System.Nullable<int> _id_rachunku;
		
		private EntitySet<goscie> _goscies;
		
		private EntityRef<fotografowie_i_kamerzysci> _fotografowie_i_kamerzysci;
		
		private EntityRef<orkiestry> _orkiestry;
		
		private EntityRef<pary_mlode> _pary_mlode;
		
		private EntityRef<rachunki> _rachunki;
		
		private EntityRef<sale> _sale;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_weselaChanging(int value);
    partial void Onid_weselaChanged();
    partial void On_dataChanging(System.DateTime value);
    partial void On_dataChanged();
    partial void Onid_paryChanging(int value);
    partial void Onid_paryChanged();
    partial void Onliczba_gosciChanging(int value);
    partial void Onliczba_gosciChanged();
    partial void Onid_saliChanging(System.Nullable<int> value);
    partial void Onid_saliChanged();
    partial void Onid_fotografaChanging(System.Nullable<int> value);
    partial void Onid_fotografaChanged();
    partial void Onid_orkiestryChanging(System.Nullable<int> value);
    partial void Onid_orkiestryChanged();
    partial void Onid_rachunkuChanging(System.Nullable<int> value);
    partial void Onid_rachunkuChanged();
    #endregion
		
		public wesela()
		{
			this._goscies = new EntitySet<goscie>(new Action<goscie>(this.attach_goscies), new Action<goscie>(this.detach_goscies));
			this._fotografowie_i_kamerzysci = default(EntityRef<fotografowie_i_kamerzysci>);
			this._orkiestry = default(EntityRef<orkiestry>);
			this._pary_mlode = default(EntityRef<pary_mlode>);
			this._rachunki = default(EntityRef<rachunki>);
			this._sale = default(EntityRef<sale>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_wesela", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_wesela
		{
			get
			{
				return this._id_wesela;
			}
			set
			{
				if ((this._id_wesela != value))
				{
					this.Onid_weselaChanging(value);
					this.SendPropertyChanging();
					this._id_wesela = value;
					this.SendPropertyChanged("id_wesela");
					this.Onid_weselaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_data]", Storage="__data", DbType="DateTime NOT NULL")]
		public System.DateTime _data
		{
			get
			{
				return this.@__data;
			}
			set
			{
				if ((this.@__data != value))
				{
					this.On_dataChanging(value);
					this.SendPropertyChanging();
					this.@__data = value;
					this.SendPropertyChanged("_data");
					this.On_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pary", DbType="Int NOT NULL")]
		public int id_pary
		{
			get
			{
				return this._id_pary;
			}
			set
			{
				if ((this._id_pary != value))
				{
					if (this._pary_mlode.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_paryChanging(value);
					this.SendPropertyChanging();
					this._id_pary = value;
					this.SendPropertyChanged("id_pary");
					this.Onid_paryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liczba_gosci", DbType="Int NOT NULL")]
		public int liczba_gosci
		{
			get
			{
				return this._liczba_gosci;
			}
			set
			{
				if ((this._liczba_gosci != value))
				{
					this.Onliczba_gosciChanging(value);
					this.SendPropertyChanging();
					this._liczba_gosci = value;
					this.SendPropertyChanged("liczba_gosci");
					this.Onliczba_gosciChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sali", DbType="Int")]
		public System.Nullable<int> id_sali
		{
			get
			{
				return this._id_sali;
			}
			set
			{
				if ((this._id_sali != value))
				{
					if (this._sale.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_saliChanging(value);
					this.SendPropertyChanging();
					this._id_sali = value;
					this.SendPropertyChanged("id_sali");
					this.Onid_saliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_fotografa", DbType="Int")]
		public System.Nullable<int> id_fotografa
		{
			get
			{
				return this._id_fotografa;
			}
			set
			{
				if ((this._id_fotografa != value))
				{
					if (this._fotografowie_i_kamerzysci.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_fotografaChanging(value);
					this.SendPropertyChanging();
					this._id_fotografa = value;
					this.SendPropertyChanged("id_fotografa");
					this.Onid_fotografaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_orkiestry", DbType="Int")]
		public System.Nullable<int> id_orkiestry
		{
			get
			{
				return this._id_orkiestry;
			}
			set
			{
				if ((this._id_orkiestry != value))
				{
					if (this._orkiestry.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_orkiestryChanging(value);
					this.SendPropertyChanging();
					this._id_orkiestry = value;
					this.SendPropertyChanged("id_orkiestry");
					this.Onid_orkiestryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_rachunku", DbType="Int")]
		public System.Nullable<int> id_rachunku
		{
			get
			{
				return this._id_rachunku;
			}
			set
			{
				if ((this._id_rachunku != value))
				{
					if (this._rachunki.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_rachunkuChanging(value);
					this.SendPropertyChanging();
					this._id_rachunku = value;
					this.SendPropertyChanged("id_rachunku");
					this.Onid_rachunkuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="wesela_goscie", Storage="_goscies", ThisKey="id_wesela", OtherKey="id_wesela")]
		public EntitySet<goscie> goscies
		{
			get
			{
				return this._goscies;
			}
			set
			{
				this._goscies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fotografowie_i_kamerzysci_wesela", Storage="_fotografowie_i_kamerzysci", ThisKey="id_fotografa", OtherKey="id_fotografa", IsForeignKey=true)]
		public fotografowie_i_kamerzysci fotografowie_i_kamerzysci
		{
			get
			{
				return this._fotografowie_i_kamerzysci.Entity;
			}
			set
			{
				fotografowie_i_kamerzysci previousValue = this._fotografowie_i_kamerzysci.Entity;
				if (((previousValue != value) 
							|| (this._fotografowie_i_kamerzysci.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fotografowie_i_kamerzysci.Entity = null;
						previousValue.weselas.Remove(this);
					}
					this._fotografowie_i_kamerzysci.Entity = value;
					if ((value != null))
					{
						value.weselas.Add(this);
						this._id_fotografa = value.id_fotografa;
					}
					else
					{
						this._id_fotografa = default(Nullable<int>);
					}
					this.SendPropertyChanged("fotografowie_i_kamerzysci");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="orkiestry_wesela", Storage="_orkiestry", ThisKey="id_orkiestry", OtherKey="id_orkiestry", IsForeignKey=true)]
		public orkiestry orkiestry
		{
			get
			{
				return this._orkiestry.Entity;
			}
			set
			{
				orkiestry previousValue = this._orkiestry.Entity;
				if (((previousValue != value) 
							|| (this._orkiestry.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._orkiestry.Entity = null;
						previousValue.weselas.Remove(this);
					}
					this._orkiestry.Entity = value;
					if ((value != null))
					{
						value.weselas.Add(this);
						this._id_orkiestry = value.id_orkiestry;
					}
					else
					{
						this._id_orkiestry = default(Nullable<int>);
					}
					this.SendPropertyChanged("orkiestry");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pary_mlode_wesela", Storage="_pary_mlode", ThisKey="id_pary", OtherKey="id_pary", IsForeignKey=true)]
		public pary_mlode pary_mlode
		{
			get
			{
				return this._pary_mlode.Entity;
			}
			set
			{
				pary_mlode previousValue = this._pary_mlode.Entity;
				if (((previousValue != value) 
							|| (this._pary_mlode.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._pary_mlode.Entity = null;
						previousValue.weselas.Remove(this);
					}
					this._pary_mlode.Entity = value;
					if ((value != null))
					{
						value.weselas.Add(this);
						this._id_pary = value.id_pary;
					}
					else
					{
						this._id_pary = default(int);
					}
					this.SendPropertyChanged("pary_mlode");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="rachunki_wesela", Storage="_rachunki", ThisKey="id_rachunku", OtherKey="id_rachunku", IsForeignKey=true)]
		public rachunki rachunki
		{
			get
			{
				return this._rachunki.Entity;
			}
			set
			{
				rachunki previousValue = this._rachunki.Entity;
				if (((previousValue != value) 
							|| (this._rachunki.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._rachunki.Entity = null;
						previousValue.weselas.Remove(this);
					}
					this._rachunki.Entity = value;
					if ((value != null))
					{
						value.weselas.Add(this);
						this._id_rachunku = value.id_rachunku;
					}
					else
					{
						this._id_rachunku = default(Nullable<int>);
					}
					this.SendPropertyChanged("rachunki");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sale_wesela", Storage="_sale", ThisKey="id_sali", OtherKey="id_sali", IsForeignKey=true)]
		public sale sale
		{
			get
			{
				return this._sale.Entity;
			}
			set
			{
				sale previousValue = this._sale.Entity;
				if (((previousValue != value) 
							|| (this._sale.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._sale.Entity = null;
						previousValue.weselas.Remove(this);
					}
					this._sale.Entity = value;
					if ((value != null))
					{
						value.weselas.Add(this);
						this._id_sali = value.id_sali;
					}
					else
					{
						this._id_sali = default(Nullable<int>);
					}
					this.SendPropertyChanged("sale");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_goscies(goscie entity)
		{
			this.SendPropertyChanging();
			entity.wesela = this;
		}
		
		private void detach_goscies(goscie entity)
		{
			this.SendPropertyChanging();
			entity.wesela = null;
		}
	}
}
#pragma warning restore 1591
